stages:
  - test

build_image:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - apk add --no-cache docker-compose
    - docker-compose up -d
    - docker exec userapp python -m pytest app
