FROM python:latest

WORKDIR /app

COPY ./app /app
COPY poetry.lock pyproject.toml ./

RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install


CMD ["poetry", "run", "python", "-m", "pytest"]
